### ISSUE TITLE
Compat with Farmers Delight?

### ISSUE THREAD

**Issue by Heamaci** [Klyser8/Eggstra#2]
Could you add compatibility with Farmers Delight? They also have a fried egg recipe that gets overridden by this mod's fried egg. I would suggest making it so that Farmer's Delight's fried egg recipe overrides the one from this mod when both are installed.

**Comment by Klyser8** [comment]
I'll see what I can do, as a temporary solution though you can try deleting the recipe file from the mod's jar and see if that does anything.

**Comment by Klyser8** [comment]
Alright, no need for a temporary solution! Fried eggs are now in the forge/fabric `cooked_eggs` tag. This means that any recipes using fried eggs in Farmer's Delight can use Eggstra fried eggs. I will close the issue once the update is released!

There's no way for me to have Farmer's Delight's recipe override Eggstra's, I hope this solution works anyway (:

**Comment by Klyser8** [comment]
Update's out, if you need further assistance feel free to join my [discord server](https://discord.gg/Rp2WaKq) :)

**Comment by Heamaci** [comment]
Thank you! :D
